MODULE_TOPDIR = ../..

PGM = r.class.breaks

LIBES = $(ARRAYSTATSLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB) $(PARSONLIB)
DEPENDENCIES = $(ARRAYSTATSDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
